"""Add marks column to ExamAnalysis

Revision ID: be9fdb49e0dc
Revises: 
Create Date: 2026-04-29 15:27:40.306325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9fdb49e0dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_analyses', schema=None) as batch_op:
        batch_op.drop_column('marks')

    # ### end Alembic commands ###
